platform :ios, '8.0'
target 'EJZExhibitionUser' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'YYKit', '~> 1.0.9'
pod 'Masonry', '~> 1.0'
pod 'ReactiveObjC', '~> 3.0'

end
